export const REQUEST_ADD_BENEFICIARY = "REQUEST_ADD_BENEFICIARY"
export const ADD_BENEFICIARY_RESPONSE = "ADD_BENEFICIARY_RESPONSE"
export const ADD_BENEFICIARY_FAILED = "ADD_BENEFICIARY_FAILED"


export const REQUEST_FETCH_BENEFICIARY = "REQUEST_FETCH_BENEFICIARY"
export const FETCH_BENEFICIARY_RESPONSE = "FETCH_BENEFICIARY_RESPONSE"
export const FETCH_BENEFICIARY_FAILED = "FETCH_BENEFICIARY_FAILED"


export const REQUEST_BENEFICIARY = "REQUEST_BENEFICIARY"
export const BENEFICIARY_RESPONSE = "BENEFICIARY_RESPONSE"
export const BENEFICIARY_FAILED = "BENEFICIARY_FAILED"
