export const REQUEST_ADD_USER = "REQUEST_ADD_USER"
export const ADD_USER_RESPONSE = "ADD_USER_RESPONSE"
export const ADD_USER_FAILED = "ADD_USER_FAILED"


export const REQUEST_FETCH_USER = "REQUEST_FETCH_USER"
export const FETCH_USER_RESPONSE = "FETCH_USER_RESPONSE"
export const FETCH_USER_FAILED = "FETCH_USER_FAILED"
